[package]
name = "wasm"
version = "0.1.0"
authors = ["m-lima <marcelowind@gmail.com>"]
edition = "2018"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
chess = "3.1.1"
js-sys = "0.3"
wasm-bindgen = "0.2"
